version: "3.9"

services:
  couchbase:
    image: couchbase:community
    container_name: couchbase
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "11210:11210"
    volumes:
      - couchbase_data:/opt/couchbase/var
    environment:
      - CB_USERNAME=admin
      - CB_PASSWORD=123456
      - CB_BUCKETNAME=todo-app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8091" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - todolist-network


networks:
  todolist-network:

volumes:
  couchbase_data: